---
title: "plotly"
author: "Rebecca Silva"
date: "10/22/2019"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```

to zoom in, filter groups, hovering

Interactive graphics 

# lets make some plots
```{r}
set.seed(1)

data(nyc_airbnb)
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)  %>% 
  sample_n(5000) # bc its still so big only want sample 
```


```{r}
nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers", # marker is put a point on observation but dont connect the dots 
    color = ~price, text = ~text_label, alpha = 0.5)
```

```{r}
common_neighborhoods =
  nyc_airbnb %>% 
  count(neighbourhood, sort = TRUE) %>% 
  top_n(8) %>% 
  select(neighbourhood)

inner_join(nyc_airbnb, common_neighborhoods, by = "neighbourhood") %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")
```

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```




---- 

```{r}
set.seed(1)
data("instacart")
# most popular hour of day of the week 
# reorder vs not 
# how order of adding to cart is related to 
# days since prior order?
cart = instacart %>%  sample_n(5000)
```

```{r}
# scatter order_number vs days since prior 
cart %>%
  mutate(text_label = str_c("Price: $", aisle_id, '\nRating: ', order_number)) %>% 
  plot_ly(
    x = ~order_number, y = ~days_since_prior_order, type = "scatter", mode = "markers", # marker is put a point on observation but dont connect the dots 
    color = ~department, text = ~text_label, alpha = 0.5)

# change dow to factor 
cart %>% 
  mutate(order_dow = factor(order_dow, 
                      levels = c(0:6), 
                      labels = c("Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday")))%>% 
  plot_ly(y = ~order_hour_of_day, color = ~order_dow, type = "box")

#number of orders of product  and something like order_number 
cart %>% 
  plot_ly(x = ~product_name, color = ~order_dow, type = "box")
```

